### ISSUE TITLE
File upload optimization

### ISSUE THREAD

**Issue by vheuken** [vheuken/moomoo#1]
Currently, files are uploaded and saved with the filename as a UUID. If two of the exact same files are uploaded, they are both saved as separate files.

Later, we should save the files as their md5 checksum. When a user attenpts uploads a new file, send the checksum first and check if it already exists. If it does, just use the existing file.

**Comment by swloper** [comment]
See: xxHash, CityHash, MetroHash, FarmHash.

**Comment by swloper** [comment]
Reminder to include pictures.
