### ISSUE TITLE
Cache music to disk

### ISSUE THREAD

**Issue by vheuken** [vheuken/moomoo#10]
Right now, all of the music is stored in memory. This becomes a problem when rooms have a lot of tracks. 

We should have a maximum of 500 MB of data loaded into memory at any given time. The rest should be on the disk. 

Our immediate options for caching to disk are IndexedDB and PouchDB. 

PouchDB uses IndexedDB on the backend (falling back to WebSQL) and provides a NoSQL interface. The API is much cleaner than IndexedDB and it is tested on many browsers.

**Comment by swloper** [comment]
No solid cross-platform way to enable caching. Will require a filesystem API.
