### ISSUE TITLE
Downloads are fucked

### ISSUE THREAD

**Issue by vheuken** [vheuken/moomoo#11]
A ton of downloads end up being broken. All the broken downloads seem to download at 200%, so what is probably happening is we're getting two downloads for the same track. This shouldn't be happening.

**Comment by swloper** [comment]
~~Server crashes~~ Clients break if upload starts and completes while client is downloading.

Steps to recreate:
1- Upload song.
2- Ensure at least one client is downloading.
3- Upload a second song, ensuring the upload will complete before the client in step 2 finishes download.
4- ~~The server will crash~~ Clients will break.
