### ISSUE TITLE
Japanese characters make the song box slightly larger

### ISSUE THREAD

**Issue by dcmaradiaga** [vheuken/moomoo#148]
Uploading a song with Japanese characters make the box much larger. Larger size persists for newer songs with or without Japanese characters.

**Comment by dcmaradiaga** [comment]
Bug demonstrated here.
https://scontent-atl3-1.xx.fbcdn.net/hphotos-xpt1/v/t34.0-12/12648028_10208733825725659_871361927_n.jpg?oh=ec24071f1e66fe72c02aa1ed9bd94a6a&oe=56AD17A2

**Comment by vheuken** [comment]
Can't repro on Linux. Will try Windows.

**Comment by swloper** [comment]
Adding to #72
