### ISSUE TITLE
Play/pause button does not follow current song state.

### ISSUE THREAD

**Issue by swloper** [vheuken/moomoo#22]
Play/pause button does not change when a song starts playing on its own - remains as a "play" icon after pause when a new song is started, for example via next/previous or deleting track.

Steps to recreate:
- Upload at least two songs.
- Pause the current song.
- Hit next/previous - if there is a song after the current, deleting the current song also works.
- Play/pause button will still show "play" and will still issue a play command when pressed, then change to a pause icon and work as expected.

**Comment by vheuken** [comment]
Fixed in c45b93f6e9366bccb890049bfff0c35c201e1199
