### ISSUE TITLE
Last song on list will not repeat if user joins after last song has already finished.

### ISSUE THREAD

**Issue by swloper** [vheuken/moomoo#23]
Steps to recreate:
- Add music to list
- Finish last song on list
- Join with a new user
- Click "restart" with any user

All controls work, but the new user will receive "Uncaught TypeError: Cannot read property 'playState' of null" This is corrected if the track is ever changed.

**Comment by vheuken** [comment]
Fixed in 2da9dcf4a68d3c33239c35bbdecad7b3f73b96d7
