### ISSUE TITLE
First song on playlist breaks on first play, works afterward

### ISSUE THREAD

**Issue by swloper** [vheuken/moomoo#24]
Steps to recreate:
- Upload two tracks.
- First track will not play correctly
- Issuing a "next" command will start the second track
- Starting the first track now works.

Likely behavior:
Downloads are not being checked for completion, but rather if they exist. Incomplete files are thus being sent to SM2 to play. On reloading the track, the full file is passed to SM2.

**Comment by vheuken** [comment]
Fixed in  d29f53bf446f9f64bb79d280d465045f8f1435b4
