### ISSUE TITLE
Highlighted track position does not change when earlier track is deleted.

### ISSUE THREAD

**Issue by swloper** [vheuken/moomoo#27]
Steps to recreate:
- Upload several tracks.
- Play until midway through the playlist.
- Delete a track earlier than the highlighted track.
- Current track works as expected, but the highlighted track is now whichever track was in the position of the old earlier highlighted track.
- Self corrects on upload/download or track change.

**Comment by vheuken** [comment]
Fixed in 3b0cc61fd2b9e58dec40a02c6c4a959ad1a07e6f
