### ISSUE TITLE
Track will not start for new users.

### ISSUE THREAD

**Issue by vheuken** [vheuken/moomoo#45]

**Comment by swloper** [comment]
~~Steps to reproduce:~~
~~\- Upload at least one song.~~
~~\- After the track has started, have an additional user join. The track will start for the second user.~~
~~\- Have a third user join. The track will not start for the third user.~~

Issue resolved, replaced by similar issue.

**Comment by swloper** [comment]
Steps to reproduce:
-Upload at least one song.
-After the track has started, have an additional user join. The track will not start.
