### ISSUE TITLE
Invoking next/previous track too quickly causes various issues

### ISSUE THREAD

**Issue by swloper** [vheuken/moomoo#46]
Steps to reproduce using UI:
-Upload several (10) tracks
-Click "next track" or "previous track" quickly (~50ms between clicks)
-Sometimes a track that has been selected will continue to play after hitting "next/previous" again, other times the UI will scroll through too many or too few tracks.

**Comment by vheuken** [comment]
Can't reproduce. Can you double check?

**Comment by vheuken** [comment]
Scratch that; I can repro.
