### ISSUE TITLE
Final polish for 0.1

### ISSUE THREAD

**Issue by swloper** [vheuken/moomoo#72]
So far:
- [x] Add track length
- [x] Add track filetype
- [x] Properly center sign-in input
- [x] Properly center player controls
- [x] Fix inconsistent album art size
- [x] Only show allowed file types in file select dialog 
- [x] Correct fonts. Text entry box should be Noto Sans.
- [x] Fix volume control position
- [x] Replace blank names with an indicator for anonymous users
- [x] Change cursor accordingly when hovering over playlist item and dragging.
- [x] Track ball doesn't obey boundaries when window is resized and no track has been uploaded
- [ ] Bottom area with upload slots and volume goes off bottom of page
- [ ] Resizing does not work
- [ ] Force consistent track view height 
- [ ] Remove Blake from player buttons

**Comment by vheuken** [comment]
I'll add to this list as I see fit

**Comment by vheuken** [comment]
"Replace blank names with an indicator for anonymous users"  will give all anonymous users the same name. This will be fixed implicitly when we handle duplicate usernames.
