### ISSUE TITLE
Pause/Cancel issues

### ISSUE THREAD

**Issue by swloper** [vheuken/moomoo#92]
Steps to reproduce:
- Start uploading 4 tracks with a limit of 2
- Pause or cancel track 4
- Track 3 will start uploading despite the limit of 2
- Pausing or cancelling any track two or more below the next track in the queue will start the next track in the queue

Alternate steps:
- Start uploading N tracks with a limit of 2
- Pause track 3
- Track 3 will start, and track 4 will be paused instead
- Pausing or cancelling the next track in the queue will pause the track after it, instead starting the track that was paused

**Comment by vheuken** [comment]
Fixed the pause part of it.

**Comment by vheuken** [comment]
....and fixed the cancel part of it.
